first-iteration
just4fun-xd/go-db-sql-final pull request #1
Opened 2024-07-29 14:27 UTC by just4fun-xd

2024-07-29 15:01 UTC, just-musha requested changes
Привет! Неплохая работа, есть несколько вещей, что нужно поправить. Главное - это корректная работа с БД.  Присылай правки и будетд апрув!

2024-07-29 15:01 UTC, just-musha commented on main.go
> +		fmt.Println(err)
Тут return не потерялся?

2024-07-29 15:01 UTC, just-musha commented on parcel.go
> +	}
После цикла на забыть проверить rows.Err

2024-07-29 15:01 UTC, just-musha commented on parcel_test.go
> +		require.Equal(t, parcelMap[num], parcel)
:+1: хорошо что сравниваешь целиком структуры

2024-07-29 15:01 UTC, just-musha commented on parcel_test.go
> +	if err != nil {
Эта проверка не нужна. Можно сразу делать `require`

2024-07-29 15:01 UTC, just-musha commented on parcel_test.go
> +	require.Equal(t, sql.ErrNoRows, err)
:+1: круто что проверяшь саму ошибку

2024-07-30 06:54 UTC, just-musha approved these changes
Спасибо! Принято! Успехов дальше!

2024-07-30 06:54 UTC, just-musha commented on parcel.go
> +		return res, err
Тут лучше волзвращать пустой слайс. В res могут быть битые данные, если произошла ошибка

2024-07-30 07:17 UTC, just4fun-xd commented on parcel.go
> +		return res, err
Вам спасибо за ревью )

2024-09-19 17:30 UTC, merged